#!/usr/bin/env python3
"""Disassemble the fixed four-byte LR35902 cartridge entry sequence."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ENTRY_OFFSET = 0x100
ENTRY_SIZE = 4


def decode(raw: bytes) -> dict:
    if len(raw) != ENTRY_SIZE:
        raise ValueError("entry sequence must be exactly four bytes")
    if raw[0] != 0x00 or raw[1] != 0xC3:
        raise ValueError("entry sequence is not NOP followed by JP nn")
    target = raw[2] | raw[3] << 8
    return {
        "schema_version": 1,
        "entry_offset": ENTRY_OFFSET,
        "entry_bytes": raw.hex(),
        "entry_bytes_sha256": hashlib.sha256(raw).hexdigest(),
        "instructions": [
            {"address": 0x0100, "bytes": "00", "mnemonic": "nop", "size": 1},
            {"address": 0x0101, "bytes": raw[1:].hex(), "mnemonic": "jp", "operand": target, "size": 3},
        ],
        "target_address": target,
    }


def analyze(data: bytes, expected_sha256: str | None = None) -> dict:
    digest = hashlib.sha256(data).hexdigest()
    if expected_sha256 and digest.lower() != expected_sha256.lower():
        raise ValueError("ROM SHA-256 mismatch")
    if len(data) < ENTRY_OFFSET + ENTRY_SIZE:
        raise ValueError("ROM is too short for the cartridge entry sequence")
    result = decode(data[ENTRY_OFFSET:ENTRY_OFFSET + ENTRY_SIZE])
    result.update({"source_size": len(data), "source_sha256": digest})
    return result


def omit_raw_bytes(result: dict) -> dict:
    cleaned = json.loads(json.dumps(result))
    cleaned.pop("entry_bytes", None)
    for instruction in cleaned["instructions"]:
        instruction.pop("bytes", None)
    return cleaned


def render_rgbds(result: dict, section_name: str = "Cartridge Entry") -> str:
    target = result["target_address"]
    return (
        "; Generated by tools/disassemble_gb_entry.py; do not edit by hand.\n"
        f'SECTION "{section_name}", ROM0[$0100]\n\n'
        "CartridgeEntry::\n"
        "    nop\n"
        f"    jp ${target:04x}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", type=Path)
    parser.add_argument("--expected-sha256")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--asm-output", type=Path)
    parser.add_argument("--section-name", default="Cartridge Entry")
    parser.add_argument("--omit-raw-bytes", action="store_true")
    args = parser.parse_args()
    try:
        result = analyze(args.rom.read_bytes(), args.expected_sha256)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    report = omit_raw_bytes(result) if args.omit_raw_bytes else result
    text = json.dumps(report, indent=2) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        print(text, end="")
    if args.asm_output:
        args.asm_output.write_text(
            render_rgbds(result, args.section_name), encoding="utf-8", newline="\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
