#!/usr/bin/env python3
"""Disassemble one conservative LR35902 basic block from a verified ROM."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


SIMPLE = {
    0x00: ("nop", 1, False),
    0x78: ("ld a, b", 1, False),
    0xAF: ("xor a", 1, False),
    0xB1: ("or c", 1, False),
    0xF3: ("di", 1, False),
    0x23: ("inc hl", 1, False),
    0x0B: ("dec bc", 1, False),
    0xC9: ("ret", 1, True),
}
IMM8 = {
    0x36: "ld [hl], ${value:02x}",
    0x3E: "ld a, ${value:02x}",
    0xFE: "cp ${value:02x}",
    0xE0: "ldh [$ff00 + ${value:02x}], a",
}
IMM16 = {0x01: "ld bc, ${value:04x}", 0x21: "ld hl, ${value:04x}", 0x31: "ld sp, ${value:04x}", 0xCD: "call ${value:04x}"}
RELATIVE = {0x18: ("jr", True), 0x20: ("jr nz", True), 0x28: ("jr z", True)}


def signed8(value: int) -> int:
    return value - 0x100 if value & 0x80 else value


def disassemble(data: bytes, start_offset: int, max_bytes: int = 0x100) -> dict:
    if not 0 <= start_offset < len(data):
        raise ValueError("start offset is outside the ROM")
    offset = start_offset
    instructions = []
    while offset < len(data) and offset - start_offset < max_bytes:
        opcode = data[offset]
        if opcode in SIMPLE:
            source, size, terminator = SIMPLE[opcode]
            target = None
        elif opcode in IMM8:
            if offset + 2 > len(data):
                raise ValueError("truncated immediate instruction")
            size, terminator, target = 2, False, None
            source = IMM8[opcode].format(value=data[offset + 1])
        elif opcode in IMM16 or opcode == 0xC3:
            if offset + 3 > len(data):
                raise ValueError("truncated 16-bit instruction")
            value = data[offset + 1] | data[offset + 2] << 8
            size = 3
            target = value
            terminator = opcode == 0xC3
            source = f"jp ${value:04x}" if opcode == 0xC3 else IMM16[opcode].format(value=value)
        elif opcode in RELATIVE:
            if offset + 2 > len(data):
                raise ValueError("truncated relative branch")
            size, terminator = 2, RELATIVE[opcode][1]
            target = (offset + size + signed8(data[offset + 1])) & 0xFFFF
            source = f"{RELATIVE[opcode][0]} ${target:04x}"
        else:
            raise ValueError(f"unsupported opcode 0x{opcode:02x} at 0x{offset:04x}")
        raw = data[offset:offset + size]
        item = {"address": offset, "bytes": raw.hex(), "opcode": opcode, "size": size, "source": source}
        if target is not None:
            item["target_address"] = target
        instructions.append(item)
        offset += size
        if terminator:
            break
    if not instructions or not terminator:
        raise ValueError("no basic-block terminator found within scan limit")
    raw = data[start_offset:offset]
    return {
        "schema_version": 1,
        "start_address": start_offset,
        "end_address": offset,
        "byte_length": len(raw),
        "instruction_count": len(instructions),
        "block_bytes": raw.hex(),
        "block_bytes_sha256": hashlib.sha256(raw).hexdigest(),
        "instructions": instructions,
        "terminator": instructions[-1]["source"],
    }


def analyze(data: bytes, start_offset: int, expected_sha256: str | None = None, max_bytes: int = 0x100) -> dict:
    digest = hashlib.sha256(data).hexdigest()
    if expected_sha256 and digest.lower() != expected_sha256.lower():
        raise ValueError("ROM SHA-256 mismatch")
    result = disassemble(data, start_offset, max_bytes)
    result.update({"source_size": len(data), "source_sha256": digest})
    return result


def render_rgbds(
    result: dict,
    section_name: str = "Entry Target Block",
    label: str = "EntryTargetBlock",
) -> str:
    start = result["start_address"]
    lines = [
        "; Generated by tools/disassemble_gb_basic_block.py; do not edit by hand.",
        f'SECTION "{section_name}", ROM0[${start:04x}]',
        "",
        f"{label}::",
    ]
    lines.extend(f"    {item['source']}" for item in result["instructions"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", type=Path)
    parser.add_argument("--start-offset", type=lambda value: int(value, 0), required=True)
    parser.add_argument("--expected-sha256")
    parser.add_argument("--max-bytes", type=lambda value: int(value, 0), default=0x100)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--asm-output", type=Path)
    parser.add_argument("--section-name", default="Entry Target Block")
    parser.add_argument("--label", default="EntryTargetBlock")
    args = parser.parse_args()
    try:
        result = analyze(args.rom.read_bytes(), args.start_offset, args.expected_sha256, args.max_bytes)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    text = json.dumps(result, indent=2) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        print(text, end="")
    if args.asm_output:
        args.asm_output.write_text(
            render_rgbds(result, args.section_name, args.label),
            encoding="utf-8",
            newline="\n",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
