#!/usr/bin/env python3
"""Build a depth-bounded LR35902 control-flow graph from verified ROM bytes."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from disassemble_gb_basic_block import disassemble


def successors(block: dict) -> list[tuple[str, int]]:
    last = block["instructions"][-1]
    source = last["source"]
    if source.startswith(("jr nz ", "jr z ")):
        return [("branch", last["target_address"]), ("fallthrough", block["end_address"])]
    if source.startswith(("jr ", "jp ")):
        return [("branch", last["target_address"])]
    return []


def build_cfg(data: bytes, start: int, max_depth: int = 1) -> dict:
    if max_depth < 0:
        raise ValueError("max depth must be non-negative")
    queue = [(start, 0)]
    blocks: dict[int, dict] = {}
    edges = []
    while queue:
        address, depth = queue.pop(0)
        if address in blocks:
            continue
        block = disassemble(data, address)
        block["depth"] = depth
        blocks[address] = block
        for kind, target in successors(block):
            edges.append({"source": address, "target": target, "kind": kind})
            if depth < max_depth and target not in blocks:
                queue.append((target, depth + 1))
    return {
        "schema_version": 1,
        "start_address": start,
        "max_depth": max_depth,
        "blocks": [blocks[address] for address in sorted(blocks)],
        "edges": sorted(edges, key=lambda edge: (edge["source"], edge["kind"], edge["target"])),
    }


def analyze(data: bytes, start: int, expected_sha256: str | None, max_depth: int) -> dict:
    digest = hashlib.sha256(data).hexdigest()
    if expected_sha256 and digest.lower() != expected_sha256.lower():
        raise ValueError("ROM SHA-256 mismatch")
    result = build_cfg(data, start, max_depth)
    result.update({"source_size": len(data), "source_sha256": digest})
    return result


def render_rgbds(result: dict, section_name: str = "Entry CFG") -> str:
    blocks = result["blocks"]
    lines = ["; Generated by tools/disassemble_gb_cfg.py; do not edit by hand."]
    for block in blocks:
        address = block["start_address"]
        lines.extend([
            "",
            f'SECTION "{section_name} {address:04x}", ROM0[${address:04x}]',
            "",
            f"Block_{address:04x}::",
        ])
        lines.extend(f"    {item['source']}" for item in block["instructions"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", type=Path)
    parser.add_argument("--start-offset", type=lambda value: int(value, 0), required=True)
    parser.add_argument("--max-depth", type=int, default=1)
    parser.add_argument("--expected-sha256")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--asm-output", type=Path)
    parser.add_argument("--section-name", default="Entry CFG")
    args = parser.parse_args()
    try:
        result = analyze(args.rom.read_bytes(), args.start_offset, args.expected_sha256, args.max_depth)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    text = json.dumps(result, indent=2) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        print(text, end="")
    if args.asm_output:
        args.asm_output.write_text(
            render_rgbds(result, args.section_name), encoding="utf-8", newline="\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
