#!/usr/bin/env python3
"""Build a depth-bounded LR35902 control-flow graph from verified ROM bytes."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from disassemble_gb_basic_block import disassemble


def successors(block: dict) -> list[tuple[str, int]]:
    last = block["instructions"][-1]
    source = last["source"]
    if source.startswith(("jr nz ", "jr z ")):
        return [("branch", last["target_address"]), ("fallthrough", block["end_address"])]
    if source.startswith(("jr ", "jp ")):
        return [("branch", last["target_address"])]
    return []


def build_cfg(data: bytes, start: int, max_depth: int = 1) -> dict:
    if max_depth < 0:
        raise ValueError("max depth must be non-negative")
    queue = [(start, 0)]
    entry_depth = {start: 0}
    discovered: dict[int, dict] = {}
    while queue:
        address, depth = queue.pop(0)
        if address in discovered:
            continue
        block = disassemble(data, address)
        discovered[address] = block
        for kind, target in successors(block):
            internal = block["start_address"] <= target < block["end_address"]
            if depth < max_depth and target not in entry_depth and not internal:
                entry_depth[target] = depth + 1
                queue.append((target, depth + 1))

    blocks: dict[int, dict] = {}
    edges = []
    entries = sorted(entry_depth)
    for address in entries:
        block = discovered[address]
        boundary = next(
            (entry for entry in entries if block["start_address"] < entry < block["end_address"]),
            None,
        )
        if boundary is not None:
            instructions = [item for item in block["instructions"] if item["address"] < boundary]
            if not instructions or instructions[-1]["address"] + instructions[-1]["size"] != boundary:
                raise ValueError(f"CFG entry 0x{boundary:04x} is not instruction-aligned")
            raw = data[address:boundary]
            block = {
                "schema_version": 1,
                "start_address": address,
                "end_address": boundary,
                "byte_length": len(raw),
                "instruction_count": len(instructions),
                "block_bytes": raw.hex(),
                "block_bytes_sha256": hashlib.sha256(raw).hexdigest(),
                "instructions": instructions,
                "terminator": f"fallthrough ${boundary:04x}",
            }
            block_successors = [("fallthrough", boundary)]
        else:
            block_successors = successors(block)
        block["depth"] = entry_depth[address]
        blocks[address] = block
        edges.extend(
            {"source": address, "target": target, "kind": kind}
            for kind, target in block_successors
        )
    return {
        "schema_version": 1,
        "start_address": start,
        "max_depth": max_depth,
        "blocks": [blocks[address] for address in sorted(blocks)],
        "edges": sorted(edges, key=lambda edge: (edge["source"], edge["kind"], edge["target"])),
    }


def analyze(data: bytes, start: int, expected_sha256: str | None, max_depth: int) -> dict:
    digest = hashlib.sha256(data).hexdigest()
    if expected_sha256 and digest.lower() != expected_sha256.lower():
        raise ValueError("ROM SHA-256 mismatch")
    result = build_cfg(data, start, max_depth)
    result.update({"source_size": len(data), "source_sha256": digest})
    return result


def omit_raw_bytes(result: dict) -> dict:
    """Return a publishable report without embedded ROM byte extracts."""
    cleaned = json.loads(json.dumps(result))
    for block in cleaned["blocks"]:
        block.pop("block_bytes", None)
        for instruction in block["instructions"]:
            instruction.pop("bytes", None)
            instruction.pop("opcode", None)
    return cleaned


def render_rgbds(result: dict, section_name: str = "Entry CFG") -> str:
    blocks = result["blocks"]
    lines = ["; Generated by tools/disassemble_gb_cfg.py; do not edit by hand."]
    for block in blocks:
        address = block["start_address"]
        lines.extend([
            "",
            f'SECTION "{section_name} {address:04x}", ROM0[${address:04x}]',
            "",
            f"Block_{address:04x}::",
        ])
        lines.extend(f"    {item['source']}" for item in block["instructions"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", type=Path)
    parser.add_argument("--start-offset", type=lambda value: int(value, 0), required=True)
    parser.add_argument("--max-depth", type=int, default=1)
    parser.add_argument("--expected-sha256")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--asm-output", type=Path)
    parser.add_argument("--section-name", default="Entry CFG")
    parser.add_argument("--omit-raw-bytes", action="store_true")
    args = parser.parse_args()
    try:
        result = analyze(args.rom.read_bytes(), args.start_offset, args.expected_sha256, args.max_depth)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    report = omit_raw_bytes(result) if args.omit_raw_bytes else result
    text = json.dumps(report, indent=2) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        print(text, end="")
    if args.asm_output:
        args.asm_output.write_text(
            render_rgbds(result, args.section_name), encoding="utf-8", newline="\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
